enum CartEnum {
  GET_CART = 'GET_CART',
  ADD_TO_CART = 'ADD_TO-CART',
  DELETE_FROM_CART = 'DELETE_FROM_CART',
  CART_FETCH_SUCCESS = 'CART_FETCH_SUCCESS',
  CART_FETCH_FAILURE = 'CART_FETCH_FAILURE'
}

export default CartEnum