enum OrdersActionsEnum {
  GET_ORDER_START = 'GET_ORDER-START',
  POST_ORDERS_START = 'POST_ORDER_START',
  FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS',
  FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE'
}

export default  OrdersActionsEnum