enum ProductsActionTypesEnum {
  FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START',
  FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCT_SUCCESS',
  FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCT_FAILURE',
  FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS',
  FETCH_PRODUCT_BY_ID = 'FETCH_PRODUCT_BY_ID',
  SEARCH_PRODUCT_BY_STRING = 'SEARCH_PRODUCT_BY_STRING'
}

export default ProductsActionTypesEnum;
