enum AuthEnum  {
  POST_USER_SIGN_UP = 'POST_USER_SIGN_UP',
  POST_USER_SUCCESS = 'POST_USER_SUCCESS',
  POST_USER_FAILURE = 'POST_USER_FAILURE',
  POST_USER_SIGN_IN = 'POST_USER_SIGN_IN',

}

export default AuthEnum